name: 'Workflow Processor'
description: 'Builds valid github workflows from relations between templates and workflows'
author: 'Hathoute'
inputs:
  templates-directory:
    required: false
    description: 'The directory containing the templates to use, will not scan subdirectories'
    default: './src/templates'
  workflows-directory:
    required: false
    description: 'The directory containing the workflows to use, will not scan subdirectories'
    default: './src'
  schema-directory:
    required: false
    description: 'The directory containing the schemas, you can use this to override the default schemas'
    default: '/action/schema'
  generated-directory:
    required: false
    description: 'The directory to output the generated workflows to'
    default: './generated'
  log-level:
    required: false
    description: 'The log level to use, can be [trace, debug, info, warn, error]'
    default: 'info'
  die-when-invalid:
    required: false
    description: 'Whether to die when the generated workflow is invalid, per the definition of the schema'
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
