name: Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

imports:
  - templates/template.yml
  - templates/template2.yml

jobs:
  build:
    extends: template/build
  test:
    extends: template2/test